language: php

addons:
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation
    sauce_connect: false

cache:
  directories:
    - $HOME/.composer/cache

sudo: required
dist: trusty

php:
  - 5.4
  - 5.6
  - 7.0
<<<<<<< HEAD

before_install:
  # Apache & php-fpm configuration
  - bash travis-scripts/setup-php-fpm.sh
  - bash travis-scripts/setup-apache.sh

  # PrestaShop configuration
  - cp -Rf .composer/* ~/.composer/ & composer global install;
  - cp tests/parameters.yml.travis app/config/parameters.yml
=======

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_install:
  - sudo apt-get update

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp tests/php7-pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f tests/travis-ci-apache-vhost /etc/apache2/sites-available/default
  - sudo cp -Rf . /var/www/prestashop.unit.test
  - sudo chmod 777 -R /var/www/
  - sudo service apache2 restart
>>>>>>> 81aa7fda2ffd8c747b99262ecae76fd22efddb3f

notifications:
  hipchat: ec4e21c5eb82066ba8be5fd1afefde@1184657

script:
<<<<<<< HEAD
  - composer install --prefer-dist --no-interaction --no-progress
  - bash tests/check_file_syntax.sh
  - bash travis-scripts/install-prestashop
  - php bin/phpunit -c tests/
  - SYMFONY_DEPRECATIONS_HELPER=disabled php bin/phpunit -c tests/phpunit-admin.xml
  - composer phpunit-sf
  - composer phpunit-controllers
  - bash ./travis-scripts/run-selenium-tests
  - bash ./travis-scripts/test-startertheme

after_script:
  - sudo cat /var/log/apache2/error.log

after_failure:
  - curl -L http://localhost/
  - cat /etc/apache2/envvars
  - cat /etc/apache2/sites-available/000-default.conf
  - sudo cat /var/log/php-fpm.log
  - sudo ls -l /var/log/apache2
  - sudo cat /var/log/apache2/other_vhosts_access.log
=======
  - /var/www/prestashop.unit.test/tests/check_php_parse_errors.sh
  - php /var/www/prestashop.unit.test/install-dev/index_cli.php --language=en --country=us --domain=localhost --base_uri=/prestashop.unit.test --db_name=prestashop.unit.test --db_create=1 --name=prestashop.unit.test --password=123456789
  - cd /var/www/prestashop.unit.test/tests && bash getcomposer.sh && php composer.phar install && php vendor/bin/phpunit -c .
>>>>>>> 81aa7fda2ffd8c747b99262ecae76fd22efddb3f
